version: "3"

tasks:
  default:
    cmds:
      - task: generate
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/server/*.proto --go_out=./gen --go_opt=paths=source_relative --go-grpc_out=./gen --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/server/*.proto --openapiv2_out  ./gen
      - protoc -I . --grpc-gateway_out ./gen  --grpc-gateway_opt paths=source_relative   --grpc-gateway_opt grpc_api_configuration=gen/buf.gen.yaml   --grpc-gateway_opt standalone=true    proto/server/*.proto
  
  
